# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.28

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/hughes_card/Documentos/Escuela/Redes/Proyecto/Computer-Networks

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/hughes_card/Documentos/Escuela/Redes/Proyecto/Computer-Networks

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/hughes_card/Documentos/Escuela/Redes/Proyecto/Computer-Networks/CMakeFiles /home/hughes_card/Documentos/Escuela/Redes/Proyecto/Computer-Networks//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/hughes_card/Documentos/Escuela/Redes/Proyecto/Computer-Networks/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -P /home/hughes_card/Documentos/Escuela/Redes/Proyecto/Computer-Networks/CMakeFiles/VerifyGlobs.cmake
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named linkchat

# Build rule for target.
linkchat: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 linkchat
.PHONY : linkchat

# fast build rule for target.
linkchat/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/linkchat.dir/build.make CMakeFiles/linkchat.dir/build
.PHONY : linkchat/fast

src/app.o: src/app.cpp.o
.PHONY : src/app.o

# target to build an object file
src/app.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/linkchat.dir/build.make CMakeFiles/linkchat.dir/src/app.cpp.o
.PHONY : src/app.cpp.o

src/app.i: src/app.cpp.i
.PHONY : src/app.i

# target to preprocess a source file
src/app.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/linkchat.dir/build.make CMakeFiles/linkchat.dir/src/app.cpp.i
.PHONY : src/app.cpp.i

src/app.s: src/app.cpp.s
.PHONY : src/app.s

# target to generate assembly for a file
src/app.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/linkchat.dir/build.make CMakeFiles/linkchat.dir/src/app.cpp.s
.PHONY : src/app.cpp.s

src/cli.o: src/cli.cpp.o
.PHONY : src/cli.o

# target to build an object file
src/cli.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/linkchat.dir/build.make CMakeFiles/linkchat.dir/src/cli.cpp.o
.PHONY : src/cli.cpp.o

src/cli.i: src/cli.cpp.i
.PHONY : src/cli.i

# target to preprocess a source file
src/cli.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/linkchat.dir/build.make CMakeFiles/linkchat.dir/src/cli.cpp.i
.PHONY : src/cli.cpp.i

src/cli.s: src/cli.cpp.s
.PHONY : src/cli.s

# target to generate assembly for a file
src/cli.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/linkchat.dir/build.make CMakeFiles/linkchat.dir/src/cli.cpp.s
.PHONY : src/cli.cpp.s

src/header.o: src/header.cpp.o
.PHONY : src/header.o

# target to build an object file
src/header.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/linkchat.dir/build.make CMakeFiles/linkchat.dir/src/header.cpp.o
.PHONY : src/header.cpp.o

src/header.i: src/header.cpp.i
.PHONY : src/header.i

# target to preprocess a source file
src/header.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/linkchat.dir/build.make CMakeFiles/linkchat.dir/src/header.cpp.i
.PHONY : src/header.cpp.i

src/header.s: src/header.cpp.s
.PHONY : src/header.s

# target to generate assembly for a file
src/header.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/linkchat.dir/build.make CMakeFiles/linkchat.dir/src/header.cpp.s
.PHONY : src/header.cpp.s

src/main.o: src/main.cpp.o
.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/linkchat.dir/build.make CMakeFiles/linkchat.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/linkchat.dir/build.make CMakeFiles/linkchat.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/linkchat.dir/build.make CMakeFiles/linkchat.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/net/app_eth_bind.o: src/net/app_eth_bind.cpp.o
.PHONY : src/net/app_eth_bind.o

# target to build an object file
src/net/app_eth_bind.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/linkchat.dir/build.make CMakeFiles/linkchat.dir/src/net/app_eth_bind.cpp.o
.PHONY : src/net/app_eth_bind.cpp.o

src/net/app_eth_bind.i: src/net/app_eth_bind.cpp.i
.PHONY : src/net/app_eth_bind.i

# target to preprocess a source file
src/net/app_eth_bind.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/linkchat.dir/build.make CMakeFiles/linkchat.dir/src/net/app_eth_bind.cpp.i
.PHONY : src/net/app_eth_bind.cpp.i

src/net/app_eth_bind.s: src/net/app_eth_bind.cpp.s
.PHONY : src/net/app_eth_bind.s

# target to generate assembly for a file
src/net/app_eth_bind.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/linkchat.dir/build.make CMakeFiles/linkchat.dir/src/net/app_eth_bind.cpp.s
.PHONY : src/net/app_eth_bind.cpp.s

src/net/eth_adapter.o: src/net/eth_adapter.cpp.o
.PHONY : src/net/eth_adapter.o

# target to build an object file
src/net/eth_adapter.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/linkchat.dir/build.make CMakeFiles/linkchat.dir/src/net/eth_adapter.cpp.o
.PHONY : src/net/eth_adapter.cpp.o

src/net/eth_adapter.i: src/net/eth_adapter.cpp.i
.PHONY : src/net/eth_adapter.i

# target to preprocess a source file
src/net/eth_adapter.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/linkchat.dir/build.make CMakeFiles/linkchat.dir/src/net/eth_adapter.cpp.i
.PHONY : src/net/eth_adapter.cpp.i

src/net/eth_adapter.s: src/net/eth_adapter.cpp.s
.PHONY : src/net/eth_adapter.s

# target to generate assembly for a file
src/net/eth_adapter.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/linkchat.dir/build.make CMakeFiles/linkchat.dir/src/net/eth_adapter.cpp.s
.PHONY : src/net/eth_adapter.cpp.s

src/pdu.o: src/pdu.cpp.o
.PHONY : src/pdu.o

# target to build an object file
src/pdu.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/linkchat.dir/build.make CMakeFiles/linkchat.dir/src/pdu.cpp.o
.PHONY : src/pdu.cpp.o

src/pdu.i: src/pdu.cpp.i
.PHONY : src/pdu.i

# target to preprocess a source file
src/pdu.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/linkchat.dir/build.make CMakeFiles/linkchat.dir/src/pdu.cpp.i
.PHONY : src/pdu.cpp.i

src/pdu.s: src/pdu.cpp.s
.PHONY : src/pdu.s

# target to generate assembly for a file
src/pdu.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/linkchat.dir/build.make CMakeFiles/linkchat.dir/src/pdu.cpp.s
.PHONY : src/pdu.cpp.s

src/reassembly.o: src/reassembly.cpp.o
.PHONY : src/reassembly.o

# target to build an object file
src/reassembly.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/linkchat.dir/build.make CMakeFiles/linkchat.dir/src/reassembly.cpp.o
.PHONY : src/reassembly.cpp.o

src/reassembly.i: src/reassembly.cpp.i
.PHONY : src/reassembly.i

# target to preprocess a source file
src/reassembly.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/linkchat.dir/build.make CMakeFiles/linkchat.dir/src/reassembly.cpp.i
.PHONY : src/reassembly.cpp.i

src/reassembly.s: src/reassembly.cpp.s
.PHONY : src/reassembly.s

# target to generate assembly for a file
src/reassembly.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/linkchat.dir/build.make CMakeFiles/linkchat.dir/src/reassembly.cpp.s
.PHONY : src/reassembly.cpp.s

src/sender.o: src/sender.cpp.o
.PHONY : src/sender.o

# target to build an object file
src/sender.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/linkchat.dir/build.make CMakeFiles/linkchat.dir/src/sender.cpp.o
.PHONY : src/sender.cpp.o

src/sender.i: src/sender.cpp.i
.PHONY : src/sender.i

# target to preprocess a source file
src/sender.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/linkchat.dir/build.make CMakeFiles/linkchat.dir/src/sender.cpp.i
.PHONY : src/sender.cpp.i

src/sender.s: src/sender.cpp.s
.PHONY : src/sender.s

# target to generate assembly for a file
src/sender.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/linkchat.dir/build.make CMakeFiles/linkchat.dir/src/sender.cpp.s
.PHONY : src/sender.cpp.s

src/util/crc32.o: src/util/crc32.cpp.o
.PHONY : src/util/crc32.o

# target to build an object file
src/util/crc32.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/linkchat.dir/build.make CMakeFiles/linkchat.dir/src/util/crc32.cpp.o
.PHONY : src/util/crc32.cpp.o

src/util/crc32.i: src/util/crc32.cpp.i
.PHONY : src/util/crc32.i

# target to preprocess a source file
src/util/crc32.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/linkchat.dir/build.make CMakeFiles/linkchat.dir/src/util/crc32.cpp.i
.PHONY : src/util/crc32.cpp.i

src/util/crc32.s: src/util/crc32.cpp.s
.PHONY : src/util/crc32.s

# target to generate assembly for a file
src/util/crc32.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/linkchat.dir/build.make CMakeFiles/linkchat.dir/src/util/crc32.cpp.s
.PHONY : src/util/crc32.cpp.s

src/util/helpers.o: src/util/helpers.cpp.o
.PHONY : src/util/helpers.o

# target to build an object file
src/util/helpers.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/linkchat.dir/build.make CMakeFiles/linkchat.dir/src/util/helpers.cpp.o
.PHONY : src/util/helpers.cpp.o

src/util/helpers.i: src/util/helpers.cpp.i
.PHONY : src/util/helpers.i

# target to preprocess a source file
src/util/helpers.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/linkchat.dir/build.make CMakeFiles/linkchat.dir/src/util/helpers.cpp.i
.PHONY : src/util/helpers.cpp.i

src/util/helpers.s: src/util/helpers.cpp.s
.PHONY : src/util/helpers.s

# target to generate assembly for a file
src/util/helpers.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/linkchat.dir/build.make CMakeFiles/linkchat.dir/src/util/helpers.cpp.s
.PHONY : src/util/helpers.cpp.s

src/util/mac.o: src/util/mac.cpp.o
.PHONY : src/util/mac.o

# target to build an object file
src/util/mac.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/linkchat.dir/build.make CMakeFiles/linkchat.dir/src/util/mac.cpp.o
.PHONY : src/util/mac.cpp.o

src/util/mac.i: src/util/mac.cpp.i
.PHONY : src/util/mac.i

# target to preprocess a source file
src/util/mac.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/linkchat.dir/build.make CMakeFiles/linkchat.dir/src/util/mac.cpp.i
.PHONY : src/util/mac.cpp.i

src/util/mac.s: src/util/mac.cpp.s
.PHONY : src/util/mac.s

# target to generate assembly for a file
src/util/mac.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/linkchat.dir/build.make CMakeFiles/linkchat.dir/src/util/mac.cpp.s
.PHONY : src/util/mac.cpp.s

src/util/time.o: src/util/time.cpp.o
.PHONY : src/util/time.o

# target to build an object file
src/util/time.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/linkchat.dir/build.make CMakeFiles/linkchat.dir/src/util/time.cpp.o
.PHONY : src/util/time.cpp.o

src/util/time.i: src/util/time.cpp.i
.PHONY : src/util/time.i

# target to preprocess a source file
src/util/time.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/linkchat.dir/build.make CMakeFiles/linkchat.dir/src/util/time.cpp.i
.PHONY : src/util/time.cpp.i

src/util/time.s: src/util/time.cpp.s
.PHONY : src/util/time.s

# target to generate assembly for a file
src/util/time.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/linkchat.dir/build.make CMakeFiles/linkchat.dir/src/util/time.cpp.s
.PHONY : src/util/time.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... linkchat"
	@echo "... src/app.o"
	@echo "... src/app.i"
	@echo "... src/app.s"
	@echo "... src/cli.o"
	@echo "... src/cli.i"
	@echo "... src/cli.s"
	@echo "... src/header.o"
	@echo "... src/header.i"
	@echo "... src/header.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/net/app_eth_bind.o"
	@echo "... src/net/app_eth_bind.i"
	@echo "... src/net/app_eth_bind.s"
	@echo "... src/net/eth_adapter.o"
	@echo "... src/net/eth_adapter.i"
	@echo "... src/net/eth_adapter.s"
	@echo "... src/pdu.o"
	@echo "... src/pdu.i"
	@echo "... src/pdu.s"
	@echo "... src/reassembly.o"
	@echo "... src/reassembly.i"
	@echo "... src/reassembly.s"
	@echo "... src/sender.o"
	@echo "... src/sender.i"
	@echo "... src/sender.s"
	@echo "... src/util/crc32.o"
	@echo "... src/util/crc32.i"
	@echo "... src/util/crc32.s"
	@echo "... src/util/helpers.o"
	@echo "... src/util/helpers.i"
	@echo "... src/util/helpers.s"
	@echo "... src/util/mac.o"
	@echo "... src/util/mac.i"
	@echo "... src/util/mac.s"
	@echo "... src/util/time.o"
	@echo "... src/util/time.i"
	@echo "... src/util/time.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -P /home/hughes_card/Documentos/Escuela/Redes/Proyecto/Computer-Networks/CMakeFiles/VerifyGlobs.cmake
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

